name: Lint Website

permissions:
  contents: read

on:
  push:
    paths:
      - ".github/workflows/lint-website.yml"
      - "website/**/*.md"
  pull_request:
    paths:
      - ".github/workflows/lint-website.yml"
      - "website/**/*.md"

jobs:
  lint:
    name: Lint website
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint markdown
        uses: nosborn/github-action-markdown-cli@v3.1.0
        with:
          files: ./website
          config_file: ./website/.markdownlintrc
